### ISSUE TITLE
review project5.2

### ISSUE THREAD

**Issue by shevchuknine** [7denis7denis7/reactTickets#7]
https://github.com/7denis7denis7/reactTickets/blob/991375a224c50655ee1d1298f3eb847d1888357c/tickets/src/project5.2/Components/ModalForm/ModalForm.jsx#L21
у тебя регулярка на 10 цифр с условным плюсом, скобочками и знаками между цифрами. в задании "+<12 цифр>". 
идея хорошая, просто упрости свою регулярку
_
https://github.com/7denis7denis7/reactTickets/blob/991375a224c50655ee1d1298f3eb847d1888357c/tickets/src/project5.2/Components/ModalForm/ModalForm.jsx#L25
результат операций в скобках и так уже булеан, можно возвращать его
_
https://github.com/7denis7denis7/reactTickets/blob/991375a224c50655ee1d1298f3eb847d1888357c/tickets/src/project5.2/Components/ModalForm/ModalForm.jsx#L16-L18
отложенная инициализация useState
_
с модалками у тебя получилось как-то странно: модалка создания/редактирования выступает как полноценная умная компонента (сама умеет в апи, в обновленние состояния и т.д.), а модалка удаления получилось глупая - только рендерит и пробрасывает обработчики. нужно выбрать один подход и ему следовать.
подход с умными модалками мне не кажется странным в данном случае. в принципе, если выберешь остановиться на нем - почему бы и нет.
единственное, тебе нужно поработать над названиями пропсов, должно быть понятно за что они отвечают из названия. например,
```
modal -> isOpen
contact -> initialValues
action -> onSuccessHandler
``` 
и т.д.
еще имеет смысл объединять между собой события, которые должны выполниться после добавления. у тебя есть два события updateContacts и updateCurrent, которые выполняются после обновления. их можно объеденить в функцию с названием onUpdateSuccessHandler и передавать. и сразу из названия ясно что происходит.
_
обрати внимание, что в модалке добалвения/редактирования у тебя сначала добавляется в данных на фронте контакт, потом только изменяется на сервере. на деле все должно быть наоборот

**Comment by shevchuknine** [comment]
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L71-L76
две проверки на там месте, где может быть одна: `currentContact ? <Contact/> : <List/>`
_
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/Contact/Contact.jsx#L6
ты проверяешь это на предыдущем уровне
_
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L77
у одной модалки открытие управляется снаружи, у другой внутри. ты сделал "умные" модалки, потому имеет смысл использовать состояние отображения модалки внутри компонента модалки. 
_
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/DeleteModal/DeleteModal.jsx#L34
эффективнее просто рендерить null в случае, если модалка закрыта
_
обе модалки имеют общий механизм открытия через порталы, общие стили -> выноси в отдельный компонент `Modal`, который будет рендерить тело модалки через `children`
_
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/ModalForm/ModalForm.jsx#L32
не исправил. функция валидации должна возвращать `boolean` - валидно или нет. результат проверки в скобках у тебя и есть `boolean`, т.е. ты можешь сделать `validateName  = str => str.length > 0 && str.length < 10`
_
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/ModalForm/ModalForm.jsx#L49
не понимаю зачем тут обертка в виде массива, выглядит излишней. отпиши, плз, в Телеграме идею
_
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/request/delete.js#L7
для всех запросов, которые работают с одним инстансом API (как все твои запросы, просто по разным роутам) необходимо создавать один axios instance (axios.create) и конфигурировать его один раз. в твоем случае это будет общая часть URL для всех запросов. и уже через этот инстанс обращаться в API. более удобно объеденить все запросы в один API инстанс в одном файле - но не обязательно
_
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/ModalForm/ModalForm.jsx#L53
в результате вызова этого метода модалка закроется - с именованием проблемки :)
_
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L22
мутируешь `obj`. с таким подходом можно было сразу добавлять к нему `id` еще в модалке и не мучаться. либо же `return {...obj, id}` в хендлере
_
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/DeleteModal/DeleteModal.jsx#L14
если на беке произойдет ошибка, это было посчитано зря. перемести ниже
_
https://github.com/7denis7denis7/reactTickets/blob/588699fe8762b5fca61fb9d8b3a64535bc9e0d33/tickets/src/project5.2/Components/DeleteModal/DeleteModal.jsx#L22-L24
выглядит как один проп - `onDeleteSuccess`

**Comment by shevchuknine** [comment]
https://github.com/7denis7denis7/reactTickets/blob/4f0e1f3f1614f9a59d1e799d369473f3808d5590/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L77
не до конца понял идею.
суть в том, что Modal - будет оберткой каждой отдельной модалки, т.е. если тебе нужно сделать модалку удаления, ты сделаешь компонент `DeleteModal` с таким телом: `<Modal><input value="some input"/></Modal>`.
в твоем решении, получается, что с помощью разных флагов `isOpen` для разных модалок ты регулируешь контент Modal - это ошибка.
должны получиться два разных компонента модалок, которые используют `Modal` и передают внутрь уже свой контент, который они рендерят.
_
https://github.com/7denis7denis7/reactTickets/blob/4f0e1f3f1614f9a59d1e799d369473f3808d5590/tickets/src/project5.2/Components/DeleteModal/DeleteModal.jsx#L15
сначала передаешь переменную, потом считаешь))

**Comment by 7denis7denis7** [comment]
![ScreenshottAug0320-43-53](https://user-images.githubusercontent.com/47761381/182674464-cce12003-592d-40bb-9fca-217c64352837.png)


Не могу понять почему перестало работать предварительное заполнение информации о контакте, все условия выполняются, но value у input остаются пустыми. Пока вообще никаких мыслей почему так происходит

**Comment by shevchuknine** [comment]
useState сыграл с тобой злую шутку)
когда у тебя модалка монтировалась уже с контактом, useState его читал и заполнял поля данными.
сейчас у тебя модалка монтируется, но рендерит null. но useState все-равно срабатывает и всегда с пустым контактом. получается, сейчас тебе нужен useEffect, чтобы подписаться на изменение контакта и внутри эффекта уже устанавливать состояние, которое придет из пропса

**Comment by shevchuknine** [comment]
https://github.com/7denis7denis7/reactTickets/blob/8ac90288f42f61d8551cfd95682a891f96a02375/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L31-L37
тут можно избавиться от зависимости на `isOpen` переходом на форму setIsOpen, которая принимает колбек `prevState => !prevState`
_
https://github.com/7denis7denis7/reactTickets/blob/8ac90288f42f61d8551cfd95682a891f96a02375/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L39-L45
а тут зависимости, которые в принципе не используются, от них просто можно избавиться
_
https://github.com/7denis7denis7/reactTickets/blob/8ac90288f42f61d8551cfd95682a891f96a02375/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L44
с этим состоянием ты работаешь только в модалке, просто его разбираешь. в принципе, spread тут тоже излишний
_
https://github.com/7denis7denis7/reactTickets/blob/8ac90288f42f61d8551cfd95682a891f96a02375/tickets/src/project5.2/Components/DeleteModal/DeleteModal.jsx#L16-L21
ты можешь вот эти вычисления выполнять на уровне выше, чтобы модалка в принципе не знала про список контактов,  который существует. она знает только про идентификатор того, который нужно удалить. а как только удалила, вызывает onDleeteSuccess, который на уровне выше уже фильтрует список контактов. таким образом модалка будет более грамотно оформлена, без лишней бизнес-логики
_
https://github.com/7denis7denis7/reactTickets/blob/8ac90288f42f61d8551cfd95682a891f96a02375/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L76-L89
и обрати внимание, что пропсы у тебя все еще по-разному именованы. в одном месте modal, в другом isOpen. в одном месте on...Handler, в другом просто addContact. нужно приводить к единому стилю

**Comment by shevchuknine** [comment]
https://github.com/7denis7denis7/reactTickets/blob/6b7a751f45f2b6c1953eae293c7852adda519db0/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L35
напоминаю, что если я привожу пример строчки с замечанием, то это не значит, что замечание касается только указанного куска кода. нужно вспоминать и проходить с исправлением замечания по всему проекту.
`prevState => !prevState`
_
https://github.com/7denis7denis7/reactTickets/blob/6b7a751f45f2b6c1953eae293c7852adda519db0/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L39-L45
в одном оставил `useCallback`, в другом убрал) в чем разница?)
_
https://github.com/7denis7denis7/reactTickets/blob/6b7a751f45f2b6c1953eae293c7852adda519db0/tickets/src/project5.2/Components/Wrapper/Wrapper.jsx#L96
неиспользуемый проп
